version: '3.8'

services:
  outlook-email-client:
    build: .
    container_name: outlook-email-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./accounts.json:/app/accounts.json
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      # 默认数据库配置，连接到外部PostgreSQL数据库
      - ACCOUNTS_DB_HOST=localhost
      - ACCOUNTS_DB_PORT=5432
      - ACCOUNTS_DB_USER=outlook_user
      - ACCOUNTS_DB_PASSWORD=secure_password
      - ACCOUNTS_DB_NAME=outlook_db
      - ACCOUNTS_DB_TABLE=account_backups
      - ACCOUNTS_SYNC_CONFLICT=prefer_local
      - APP_USERNAME=admin
      - APP_PASSWORD=admin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s